version: 2.1
workflows:
  testing:
    jobs:
      - runner-test


jobs:
  build:
    docker:
      - image: cimg/node:20
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm start
      - run:
          name: run build
          command: npm build

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
