version: 2.1

workflows:
  testing:
    jobs:
      - runner-test
      - runner-build-test

orbs:
  node: circleci/node@5.0.2

jobs:
  runner-test:
    machine: true
    resource_class: devillasss/circle
    steps:
      - run: echo "Hi I'm on Runners!"

  runner-build-test:
    machine: true
    resource_class: devillasss/circle
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: run build
          command: npm build

  # build:
  #   docker:
  #     - image: cimg/node:20
  #   steps:
  #     - checkout
  #     - run:
  #         name: Install Dependencies
  #         command: npm install
  #     - run:
  #         name: Run Tests
  #         command: npm start
  #     - run:
  #         name: run build
  #         command: npm build
